# Generated by Django 3.0.7 on 2021-03-14 17:47

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_control_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.TimeControlType'),
        ),
        migrations.AddField(
            model_name='game',
            name='white_player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='white_player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elo',
            name='player',
            field=annoying.fields.AutoOneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claimitem',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Claim'),
        ),
        migrations.AddField(
            model_name='claimitem',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
