# Generated by Django 3.0.7 on 2021-02-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.FileField(upload_to='')),
                ('image50', models.FileField(blank=True, default='', upload_to='')),
                ('image200', models.FileField(blank=True, default='', upload_to='')),
                ('image1000', models.FileField(blank=True, default='', upload_to='')),
                ('image2000', models.FileField(blank=True, default='', upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
